@backend_HostAddress = http://localhost:5177

### Get all products
GET {{backend_HostAddress}}/api/products
Accept: application/json

### Get a product by ID
GET {{backend_HostAddress}}/api/products/1005
Accept: application/json

### Create a new product
POST {{backend_HostAddress}}/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Wrangler Jeans",
    "description": "TEXAS - Straight leg jeans - darkstone",
    "price": 79,
    "stock": 10,
    "imageUrl": "https://img01.ztat.net/article/spp-media-p1/4a8b787eda763451a672a79d46df0e9b/a1773ff24f0940d7b7f709117778c39e.jpg?imwidth=300&filter=packshot",
    "thumbnailUrl": "https://img01.ztat.net/article/spp-media-p1/4a8b787eda763451a672a79d46df0e9b/a1773ff24f0940d7b7f709117778c39e.jpg?imwidth=50&filter=packshot",
    "categoryId": 1,
}

### Update a product
PUT {{backend_HostAddress}}/api/products/1004
Accept: application/json
Content-Type: application/json

{
  "id": 1005,
  "name": "Bershka",
  "description": "BAGGY - Relaxed fit jeans - light blue",
  "price": 276.99,
  "stock": 10,
  "imageUrl": "https://img01.ztat.net/article/spp-media-p1/40b0685382d14bfdbb0f2a0daeb67c1b/c5588d5cc61b4a59adb3210f50d2b38c.jpg?imwidth=300&filter=packshot",
  "thumbnailUrl": "https://img01.ztat.net/article/spp-media-p1/40b0685382d14bfdbb0f2a0daeb67c1b/c5588d5cc61b4a59adb3210f50d2b38c.jpg?imwidth=50&filter=packshot",
  "categoryId": 1,
}

### Get all categories
GET {{backend_HostAddress}}/api/categories
Accept: application/json

### Create a new product
POST {{backend_HostAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Women Clothing",
}

###
