@backend_HostAddress = http://localhost:5177

@API_TOKEN = {{dotenv token}}
# @API_COOKIE = {{dotenv http-cookie}}
@API_COOKIE = <<cookie_here>>

### Get all products
GET {{backend_HostAddress}}/api/products
Accept: application/json
# Authorization: Bearer {{API_TOKEN}}
Cookie: {{API_COOKIE}}

### Get a product by ID
GET {{backend_HostAddress}}/api/products/1003
Accept: application/json
# Authorization: Bearer {{API_TOKEN}}
Cookie: {{API_COOKIE}}

### Create a new product
POST {{backend_HostAddress}}/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "Wrangler Jeans",
    "description": "TEXAS - Straight leg jeans - darkstone",
    "price": 79,
    "stock": 10,
    "imageUrl": "",
    "thumbnailUrl": "",
    "categoryId": 1,
}

### Update a product
PUT {{backend_HostAddress}}/api/products/1004
Accept: application/json
Content-Type: application/json

{
  "id": 1005,
  "name": "Bershka",
  "description": "BAGGY - Relaxed fit jeans - light blue",
  "price": 276.99,
  "stock": 10,
  "imageUrl": "",
  "thumbnailUrl": "",
  "categoryId": 1,
}

### Get all categories
GET {{backend_HostAddress}}/api/categories
Accept: application/json
Authorization: Bearer {{dotenv token}}

### Get a category by ID
GET {{backend_HostAddress}}/api/categories/2
Accept: application/json
Authorization: Bearer {{dotenv token}}

### Create a new category
POST {{backend_HostAddress}}/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Women Clothing",
}


### Login
POST {{backend_HostAddress}}/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "userName": "xyz",
  "password": "xyz123"
}

###
